; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=indvars -S %s | FileCheck %s

; For every executed iteration 0 <= %i < %n, so %u = %n - 1 - %i is in [0, %n).
; %u is a no-self-wrap AddRec counting down to 0, so its minimum is the value it
; takes on the last iteration, and the range check on it folds away.

define i32 @descending_iv_bound(i64 %n, ptr %out) {
; CHECK-LABEL: define i32 @descending_iv_bound(
; CHECK-SAME: i64 [[N:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[GUARD:%.*]] = icmp sgt i64 [[N]], 0
; CHECK-NEXT:    br i1 [[GUARD]], label %[[FOR_BODY_PREHEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[FOR_BODY_PREHEADER]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[INC:%.*]], %[[FOR_BODY]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[NOT_I:%.*]] = xor i64 [[I]], -1
; CHECK-NEXT:    [[U:%.*]] = add nsw i64 [[N]], [[NOT_I]]
; CHECK-NEXT:    [[IDX:%.*]] = getelementptr inbounds nuw i64, ptr [[OUT]], i64 [[I]]
; CHECK-NEXT:    store i64 [[U]], ptr [[IDX]], align 8
; CHECK-NEXT:    [[INC]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp eq i64 [[INC]], [[N]]
; CHECK-NEXT:    br i1 [[EC]], label %[[EXIT_LOOPEXIT:.*]], label %[[FOR_BODY]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ 0, %[[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[RES]]
;
entry:
  %guard = icmp sgt i64 %n, 0
  br i1 %guard, label %for.body, label %exit

for.body:
  %bad = phi i32 [ %bad.next, %for.body ], [ 0, %entry ]
  %i = phi i64 [ %inc, %for.body ], [ 0, %entry ]
  %not.i = xor i64 %i, -1
  %u = add nsw i64 %n, %not.i
  %cmp = icmp sgt i64 %u, -1
  %bad.next = select i1 %cmp, i32 %bad, i32 1
  %idx = getelementptr inbounds nuw i64, ptr %out, i64 %i
  store i64 %u, ptr %idx, align 8
  %inc = add nuw nsw i64 %i, 1
  %ec = icmp eq i64 %inc, %n
  br i1 %ec, label %exit, label %for.body

exit:
  %res = phi i32 [ 0, %entry ], [ %bad.next, %for.body ]
  ret i32 %res
}
